import Head from 'next/head'
import Portfolio from './components/portfolio';
import {useState} from 'react'

export default function Home() {
 
 const intitalInfo = {name: 'Joe Bean',
  resumeLink:'https://docs.google.com/document/d/1lgiV3EPEmVlzx-UGieZEF6rcup2qM_2HX3_UXqJQWHM/edit',
  profession: 'Doctor',
  jobDescription:'Looking for my job as a Doctor',
  linkedInLink:'www.linkedin.com/in/kolten-bramall-b3aa24235',
  githubLink:'https://github.com/Kobramall',
  facebookLink:'https://github.com/Kobramall',
  photo:'https://media-exp1.licdn.com/dms/image/D5603AQG98_rdqBV2wg/profile-displayphoto-shrink_200_200/0/1667076531848?e=1675900800&v=beta&t=iWCtFQg9YdWBn0ZbxafaVSJDtKCNvBtucHiBLpJMMcw',
  reasonToHire:'I have performed hundreds of successful surgeries',
  email:'kbramall11@gmail.com',
  experienceDescription:'I have several real experiences',
  experienceList: {item1: "brain surgent", item2:'lung healer', item3: 'level 10 wizard'},
  skillsDescription:'I have several real experiences',
  skillsList: {item1: "brain surgent", item2:'lung healer', item3: 'level 10 wizard'},
  achievementsDescription:'I have several real experiences',
  achievementsList: {item1: "brain surgent", item2:'lung healer', item3: 'level 10 wizard'},
}
 
  const [ info, setinfo] = useState(intitalInfo)
 
  return (
    <div>
      <Head>
        <title>Kolten Bramall Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-blue-600 px-10 md:px-20 lg:px-40 dark:bg-black'>
          <Portfolio info={info}/>
      </main>
      </div>
  );
}