import Head from 'next/head'
import Portfolio from './components/portfolio';
import Form from './components/form'
import {useState} from 'react'

export default function Home() {
 
 const intitalInfo = {name:'',
  resumeLink:'',
  profession: '',
  jobDescription:'',
  linkedInLink:'',
  instagramLink:'',
  facebookLink:'',
  photo:'Drap and Drop',
  reasonToHire:'',
  email:'',
  experienceDescription:'',
  experienceList1: '',
  experienceList2: '',
  experienceList3: '',
  skillsDescription:'',
  skillsList1:'',
  skillsList2:'',
  skillsList3:'',
  achievementsDescription:'',
  achievementsList1:'' ,
  achievementsList2:'' ,
  achievementsList3:'' ,
}
 
  const [ info, setInfo] = useState(intitalInfo)
  
  const update = (inputValue, inputName) =>{


    setInfo({...info, [inputName]: inputValue})
  }

  
  const onChange = (evt) =>{
     
   const name = evt.target.name

   const {value } = evt.target

   update(value, name)

  }

  const handleDragOver= (evt) =>{
     evt.preventDefault()
  }
  
  const photoDrop = (evt) =>{
    evt.preventDefault()
    console.log(evt.dataTransfer.files)
    setInfo({...info, photo: evt.dataTransfer.files.name})
  }
 
  return (
    <div className='bg-gradient-to-br from-blue-600 to-teal-400 min-h-screen'>
      <Head>
        <title>Build Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hammer-icon.png" />
      </Head>
      <main className=' flex flex-col text-center px-10 md:px-20 lg:px-40 dark:bg-black items-center min-h-screen font-sans'>
      <div className='bg-gradient-to-l from-cyan-400 to-teal-400 p-2 mt-2 mb-2 rounded-3xl shadow-2xl'>
        <h1 className='text-6xl p-2'>Welcome to Built Portfolio</h1>
        <p className='text-2xl p-2'>Enter the info below to see a preveiw your website would look like</p>
        <p className='text-xl p-2'>(no one will see this info)</p>
      </div>
      <Form onChange={onChange} info={info} photoDrop={photoDrop} handleDragOver={handleDragOver}/>
      <div className='text-4xl p-5'>What Your Website Will Look Like</div>
      <p>(careful with clicking on links, leave the page with earse info)</p>
      <Portfolio info={info}/>
      <div className='text-2xl bg-white m-10 p-2 shadow-xl rounded-2xl'>
        <h2 className='text-6xl p-2'>Like What You See?</h2>
        <p>Get this website for your self for only $199.99 plus even more customization for free</p>
        <p>Just contact Kolten Bramall at <span className='text-orange-500'>kbramall11@gmail.com</span></p>
      </div>
      </main>
      </div>
  );
}